name: deployment-pipeline

on:
  push:
    branches:
      - workshop-3

  pull_request:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: keep it real
          run: echo "add code here"

